### ISSUE TITLE
Loading other parcellation atlas with "random rainbow" colorbar

### ISSUE THREAD

**Issue by xychen-ION** [rordenlab/MRIcroGL12#10]
Hi, 

I am using the released version of MRIcroGL for windows, great software!

MRIcroGL can load some built-in parcellations, such as AAL, and it will automatically use  the digitalized  "random rainbow" colorbar for parcellation visualization.

Here, I want to use other non-built-in parcellation and to visualize the appearance of this parcellation. However, the "random rainbow" colorbar is not activated and I can not find the options for that. I wonder if there is any solution.

Thanks and best wishes,

Xiaoyu Chen

**Comment by neurolabusc** [comment]
MRIcroGL will load atlases using a random color scheme and will use nearest-neighbor interpolation (e.g the border between area 17 and area 19 should not be labeled "18"). There are two ways to do this, either will work:
 1. Put the files you want to have viewed in this mode into a folder named "Atlases"
 2. Set the "Intention" of the image to "Labels". Assuming your image is saved as ".nii" (if it is .nii.gz, uncompress your image, you can re-compress later). You can do this by opening the image with MRIcroGL, press the "Options" button and click on the "Show Header" menu item. Click on the 'Statistics' tab, set the 'Intention' pull-down menu to "Labels', choose the "Save header" menu item from the "File" menu.

You may also want to look at some of the new atlas features available in the [beta](https://github.com/neurolabusc/MRIcroGL_AFNI) release of MRIcroGL.

**Comment by xychen-ION** [comment]
It works! Thanks for your help!
