### ISSUE TITLE
Cannot compile as simplelaz file is missing

### ISSUE THREAD

**Issue by TheChymera** [rordenlab/MRIcroGL12#12]
I am trying to compile this package, and the README indicates this should be done via the same command line script as MRIcroGL-1.0.

I use:

```
lazbuild -B --lazarusdir="/usr/share/lazarus/" --pcp="system-lazarus-config" simplelaz.lpi
```

and get: 

```
silenthost ~ # emerge -v mricrogl

 * IMPORTANT: 5 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N     ] sci-visualization/mricrogl-1.2.20190902::chymeric  0 KiB

Total: 1 package (1 new), Size of downloads: 0 KiB


>>> Verifying ebuild manifests

>>> Emerging (1 of 1) sci-visualization/mricrogl-1.2.20190902::chymeric
 * mricrogl-1.2.20190902.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                 [ ok ]
>>> Unpacking source...
>>> Unpacking mricrogl-1.2.20190902.tar.gz to /var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work
>>> Source unpacked in /var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work
>>> Preparing source in /var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work/MRIcroGL12-1.2.20190902 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work/MRIcroGL12-1.2.20190902 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work/MRIcroGL12-1.2.20190902 ...
cp: cannot stat '/etc/lazarus': No such file or directory
SetPrimaryConfigPath NewValue="system-lazarus-config" -> "/var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work/MRIcroGL12-1.2.20190902/system-lazarus-config"
Error: (lazbuild) package not found: simplelaz.lpi
 * ERROR: sci-visualization/mricrogl-1.2.20190902::chymeric failed (compile phase):
 *   (no error message)
 *
 * Call stack:
 *     ebuild.sh, line 125:  Called src_compile
 *   environment, line 785:  Called die
 * The specific snippet of code:
 *       lazbuild -B --lazarusdir="/usr/share/lazarus/" --pcp="system-lazarus-config" simplelaz.lpi || die
 *
 * If you need support, post the output of `emerge --info '=sci-visualization/mricrogl-1.2.20190902::chymeric'`,
 * the complete build log and the output of `emerge -pqv '=sci-visualization/mricrogl-1.2.20190902::chymeric'`.
 * The complete build log is located at '/var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work/MRIcroGL12-1.2.20190902'
 * S: '/var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work/MRIcroGL12-1.2.20190902'
```

The README also mentions a “Run” command, but I cannot find one inside the source code:

```
silenthost /var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work/MRIcroGL12-1.2.20190902 # find -name "*run*"
silenthost /var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work/MRIcroGL12-1.2.20190902 # find -name "*Run*"
silenthost /var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work/MRIcroGL12-1.2.20190902 # find -name "*un*"
./mainunit.pas
./mainunit.lfm
./MRIcroGL.app/Contents/Resources/matcap/unused
./MRIcroGL.app/Contents/Resources/matcap/Burgundy.jpg
./MRIcroGL.app/Contents/Resources/lut/CT_Lungs.clut
./Resources/shader/unused
./Resources/shader/ancient/unused
./Resources/matcap/unused
./Resources/matcap/Burgundy.jpg
./Resources/lut/CT_Lungs.clut
```

**Comment by neurolabusc** [comment]
The command line 
`lazbuild -B --lazarusdir="/usr/share/lazarus/" --pcp="system-lazarus-config" simplelaz.lpi`
looks like MRIcroGL1.0, for MRIcroGL1.2 the file is 'MRIcroGL.lpi'. I have never seen the other options. On my Linux machine I can compile with `lazbuild -B MRIcroGL.lpi` for the GTK2 interface, or `lazbuild -B --ws=qt5 MRIcroGL.lpi` for QT5. You might also be able to compile to GTK3, but since that does not support OpenGL multi-sampling I would use the other widgetsets.
 

I have never used Gentoo or Emerge, and since it is not providing normal error messages, I would try to do this from the command line.

what happens if you run `lazbuild --v` from the command line? I assume you are running at least Lazarus [2.0.2](https://packages.gentoo.org/packages/dev-lang/lazarus)?

Why not try this from the GUI. 
 0. Make sure you have the MetalDemos project installed - these are small modules that can be compiled independently but MRIcroGL puts them together like a bunch of legos:
   https://github.com/neurolabusc/Metal-Demos
    These should be downloaded in the same root folder as MRIcroGL, so if you have `~/MyDir/MRIcroGL12`, you should have `~/MyDir/Metal-Demos`. If not you will have to manually set the path in the MRIcroGL.lpi 
 1. startlazarus to open the GUI
 2. select Project/OpenProject menu item and open the MRIcroGL.lpi
 3. Choose Run/Run menu item

**Comment by TheChymera** [comment]
The other options are to make sure that it works with a system-wide lazarus install. I am using `=lazarus-2.0.6`.

Using 

```
lazbuild -B --lazarusdir="/usr/share/lazarus/" --pcp="system-lazarus-config" MRIcroGL.lpi
```

I get:

```
silenthost ~ # emerge -v mricrogl

 * IMPORTANT: 5 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N     ] sci-visualization/mricrogl-1.2.20190902::chymeric  0 KiB

Total: 1 package (1 new), Size of downloads: 0 KiB


>>> Verifying ebuild manifests

>>> Emerging (1 of 1) sci-visualization/mricrogl-1.2.20190902::chymeric
 * mricrogl-1.2.20190902.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                 [ ok ]
>>> Unpacking source...
>>> Unpacking mricrogl-1.2.20190902.tar.gz to /var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work
>>> Source unpacked in /var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work
>>> Preparing source in /var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work/MRIcroGL12-1.2.20190902 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work/MRIcroGL12-1.2.20190902 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work/MRIcroGL12-1.2.20190902 ...
cp: cannot stat '/etc/lazarus': No such file or directory
SetPrimaryConfigPath NewValue="system-lazarus-config" -> "/var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work/MRIcroGL12-1.2.20190902/system-lazarus-config"
SetupCompilerFilename: Searching compiler ...
SearchCompilerCandidates Value=fpc File=/usr/bin/fpc
Hint: (lazarus) [RunTool] "/usr/bin/fpc" "-iWTOTP"
Hint: (lazarus) [RunTool] "/usr/bin/fpc" "-va" "compilertest.pas"
SetupCompilerFilename: using /usr/bin/fpc
Hint: (lazarus) storing Lazarus directory "/usr/share/lazarus/" Compiler path "/usr/bin/fpc" in "/var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work/MRIcroGL12-1.2.20190902/system-lazarus-config/environmentoptions.xml"
Hint: (lazarus) [RunTool] "/usr/bin/fpc" "-iWTOTP" "-Px86_64"
Hint: (lazarus) [RunTool] "/usr/bin/fpc" "-va" "compilertest.pas" "-Px86_64"
Error: (lazbuild) Broken dependency: python4lazarus_package
 * ERROR: sci-visualization/mricrogl-1.2.20190902::chymeric failed (compile phase):
 *   (no error message)
 *
 * Call stack:
 *     ebuild.sh, line 125:  Called src_compile
 *   environment, line 785:  Called die
 * The specific snippet of code:
 *       lazbuild -B --lazarusdir="/usr/share/lazarus/" --pcp="system-lazarus-config" MRIcroGL.lpi || die
 *
 * If you need support, post the output of `emerge --info '=sci-visualization/mricrogl-1.2.20190902::chymeric'`,
 * the complete build log and the output of `emerge -pqv '=sci-visualization/mricrogl-1.2.20190902::chymeric'`.
 * The complete build log is located at '/var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work/MRIcroGL12-1.2.20190902'
 * S: '/var/tmp/portage/sci-visualization/mricrogl-1.2.20190902/work/MRIcroGL12-1.2.20190902'
```

Apparently this is the python4lazarus issue I [reported for MRIcroGL 1.0](https://github.com/neurolabusc/MRIcroGL/issues/34). As for qt5/gtk3, as discussed per email, I am indeed concerned about that, but for the time being I'm looking to just get it to work with gtk2.

**Comment by neurolabusc** [comment]
@TheChymera I have updated the README.md. Please tell me if these commands work on your distribution. Also, I have updated notes on deployment, e.g. more features if the executable can find the `Resources` folder.


```
git clone https://github.com/rordenlab/MRIcroGL12.git
git clone https://github.com/neurolabusc/Metal-Demos.git
cd MRIcroGL12
lazbuild --verbose-pkgsearch lazopenglcontext --verbose-pkgsearch python4lazarus_package
lazbuild  -B MRIcroGL.lpr

```

**Comment by TheChymera** [comment]
@neurolabusc can I install MRIcroGL1.2 without having `python4lazarus`?

**Comment by neurolabusc** [comment]
The following compiles for me:

```
git clone https://github.com/rordenlab/MRIcroGL12.git
git clone https://github.com/neurolabusc/Metal-Demos.git
cd MRIcroGL12
lazbuild --verbose-pkgsearch lazopenglcontext
lazbuild  -B MRIcroGL_NoPython.lpi
```

The resulting executable will be built without the scripting menu. The resulting user experience may be substandard. The Scripting/Templates menu item is useful to illustrate capabilities. Scripts are nice to ensure replicable figures. Scripts can be called by other tools. For example, my command line script [figures.py](https://osf.io/xvguw/) uses MRIcroGL to generate figures with scaled intensity levels.

I would think it would be worth your time to work out how to install python4lazarus using [lazbuild](https://wiki.freepascal.org/lazbuild) on your distribution. I would assume something like this would work:

```
git clone https://github.com/rordenlab/MRIcroGL12.git
git clone https://github.com/neurolabusc/Metal-Demos.git
git clone https://github.com/Alexey-T/Python-for-Lazarus.git
lazbuild --build-ide= --add-package lazopenglcontext ./Python-for-Lazarus/python4lazarus/python4lazarus_package.lpk
cd MRIcroGL12
lazbuild  -B MRIcroGL.lpr
```

**Comment by TheChymera** [comment]
@neurolabusc ok, so I am now using the latest commit 6979db2afb169523d198e973e9033b1c89ddd40b according to your instructions, and compilation does not complete, with the following [build.log](https://github.com/rordenlab/MRIcroGL12/files/4391633/build.log).

I think the issue might be 

```
/var/tmp/portage/sci-visualization/mricrogl-1.2.20200324/work/MRIcroGL12-6979db2afb169523d198e973e9033b1c89ddd40b/resize.pas(9,16) Fatal: (10022) Can't find unit SimdUtils used by resize
Fatal: (1018) Compilation aborted
```

But I'm really not sure. Any ideas?

I'll look into python4lazarus as soon as I have this more minimal version running. The issue is that we've tried to install it system-wide for lazarus, and that fails, and nobody can help me out ([upstream does not support lazbuild](https://github.com/Alexey-T/Python-for-Lazarus/issues/17), and [the Lazarus forums could not help out either](https://forum.lazarus.freepascal.org/index.php/topic,48949.0.html)). I think the only potential solution at this point (unless you have any ideas regarding system-wide support) is to try and enable python4lazarus for this package only, but as I said, it's probably best to sort everything else out first.

**Comment by neurolabusc** [comment]
I just created a clean install of Ubuntu 20.04 and with Lazarus trunk I was able to run

```
git clone https://github.com/rordenlab/MRIcroGL12.git
git clone https://github.com/neurolabusc/Metal-Demos.git
git clone https://github.com/Alexey-T/Python-for-Lazarus.git
lazbuild --build-ide= --add-package lazopenglcontext ./Python-for-Lazarus/python4lazarus/python4lazarus_package.lpk
cd MRIcroGL12
lazbuild  -B MRIcroGL.lpr
```
Are you sure you included Metal-Demos - it includes SimdUtils. From inside the MRIcroGL folder you should be able to see the unit with the relative  ls command `MRIcroGL12$ ls ../Metal-Demos/common`.
 In other words, if you have the folder ~/MRIcroGL12, you should also have the file ~/MetalDemos/common/SimdUtils.pas

**Comment by TheChymera** [comment]
Perhaps the problem is that I don't have those exact directory names. Since I am trying to package this as a static version which can specifically be referenced and installed, I'm not just cloning the current HEAD, and the directories are named according to the specific hashes. Will they then no longer be auto-detected? And if so, is there anything simpler I can do than just rename them?

```
silenthost /var/tmp/portage/sci-visualization/mricrogl-1.2.20200324/work # ls -lah
total 16K
drwx------  4 portage portage 4.0K Mar 27 01:47 .
drwx------  7 portage portage 4.0K Mar 27 01:47 ..
drwxr-xr-x 15 portage portage 4.0K Mar 24 08:12 Metal-Demos-f487b6a74a8837faa01d1f33bdcdba2e829a16c3
drwxr-xr-x  7 portage portage 4.0K Mar 27 01:47 MRIcroGL12-6979db2afb169523d198e973e9033b1c89ddd40b
```

**Comment by neurolabusc** [comment]
That would explain your issue. You can simply edit the lpi file. This is a simple xml file, so it should be easy to automate this. You need to provide the location to the Metal-Demos common folder. By default it is:
```
  <OtherUnitFiles Value="../Metal-Demos/common;../static/x86_64-win64"/>
```
So for you it would be

```
<OtherUnitFiles Value="../Metal-Demos-f487b6a74a8837faa01d1f33bdcdba2e829a16c3;../static/x86_64-win64"/>
```

You can ignore the static folder - that is an optional acceleration specific to the Windows operating system,

**Comment by TheChymera** [comment]
@neurolabusc ok, that worked, thank you :)

I'll leave this open in case I want to include python4lazarus support.

**Comment by neurolabusc** [comment]
Did you try explicitly downloading and building Python? I do think the user experience will be substandard without this. If lazbuild fails with the script below, I would open a [python4lazarus](https://github.com/Alexey-T/Python-for-Lazarus/tree/master/python4lazarus) issue.

```
git clone https://github.com/rordenlab/MRIcroGL12.git
git clone https://github.com/neurolabusc/Metal-Demos.git
git clone https://github.com/Alexey-T/Python-for-Lazarus.git
lazbuild --build-ide= --add-package lazopenglcontext ./Python-for-Lazarus/python4lazarus/python4lazarus_package.lpk
cd MRIcroGL12
lazbuild  -B MRIcroGL.lpr

```

**Comment by TheChymera** [comment]
@neurolabusc having solved the previous issue, I also enabled python-for-lazarus, and it builds fine. thanks! :)

**Comment by neurolabusc** [comment]
Great. I have just pushed a new release (v1.2.20200331). I would suggest that MRIcroGL is installed with the latest version of dcm2niix (v1.0.20200331). If MRIcroGL finds dcm2niix, the user will be able to use the Import menu to convert DICOM data, and drag-and-drop DICOM images for quick viewing.

Please close this issue if this resolves your issues.
