### ISSUE TITLE
Warning, not all volumes loaded

### ISSUE THREAD

**Issue by irxugen** [rordenlab/MRIcroGL12#15]
Hi, I hope this is the right place to ask for help.

I'm using the latest precompiled version and whenever I try to open 4D nii.gz files (from bold fmri runs), a little window pops up, with the message "**Warning: Loaded X out of 527 volumes**".

Some more details:
- When I convert my DICOMS to a nii.gz using dcm2niix, MRIcroGL manages to load the first 30 out of the 527 volumes.
- When I try to view the preprocessed nii.gz file (fmriprep), it only loads the first 3 out of 527 volumes
- The size difference from original to preprocessed is roughly a factor of 10 (70MB vs 640MB). Could this be a memory issue?

Could provide the nifti files privately, if needed.
Thanks in advance!

**Comment by neurolabusc** [comment]
In the Preferences window you have a checkbox named "Only initial volumes (load 4D series faster)". If this option is checked, only the first images are loaded, which is faster and it will require less RAM. If this option is unchecked, the entire 4D volume will be loaded. It is up to you which option you prefer.

I am surprised the fmriprep is supersampling the data to be so large. You may want to check frmiprep [settings](https://fmriprep.readthedocs.io/en/stable/spaces.html) for the bounding box and the resolution.

**Comment by irxugen** [comment]
Thanks a lot for the quick answer! 
Yes, I was already wondering. I'm pretty new to this field and am still learning. Will definitely go check for that.
