### ISSUE TITLE
Background transparent in bitmaps preference resets

### ISSUE THREAD

**Issue by apiccirilli** [rordenlab/MRIcroGL12#16]
On macOS 10.15, the option for "Background transparent in bitmaps" always resets back to false on reopening MRIcroGL. In MRIcroGL.ini, there is no ScreenCaptureTransparentBackground field, and adding that field manually to the ini file has no effect (ScreenCaptureTransparentBackground=1 in the [BOOL] section).

**Comment by neurolabusc** [comment]
Acknowledged. I have uploaded an updated version named [MRIcroGL_macOS_issue16.dmg
](https://github.com/rordenlab/MRIcroGL12/releases/tag/v1.2.20200331) for MacOS. The bitmap transparency preferences are now persistent. 

In addition to using the Prefernces window, you can now also set this property using in Python scripts using the gl.bmptransparent() function to make the background opaque (0) or transparent (1), so a minimal script would be:

```
import gl
gl.bmptransparent(1)
```

**Comment by grandjeanlab** [comment]
Hi Chris. 
could we have this option for other versions too (esp. Linux)? 
current version returns: AttributeError: module 'gl' has no attribute 'bmptransparent'

**Comment by neurolabusc** [comment]
Included in pre-release and subsequent [releases](https://github.com/rordenlab/MRIcroGL12/releases).
