### ISSUE TITLE
Python scripting broken with Python 3.9

### ISSUE THREAD

**Issue by pmediano** [rordenlab/MRIcroGL12#20]
As per the title. Using the latest pre-compiled Linux release, opening or trying to run any script (either through the GUI or the command-line options) makes this error pop out:

```
Error: could not find symbol "PyImport_Cleanup"
Python could not be properly initialized. We must quit.
```

And then MRIcroGL proceeds to fail abruptly with an access violation. This is probably because `PyImport_Cleanup` has been [removed after Python 3.8](https://docs.python.org/3/whatsnew/3.9.html#removed). Just to double-check, I installed Python 3.8 (via `pyenv`), updated the `PyLib` in the `MRIcroGL12.ini` file, and scripting works as normal again.

PS: MRIcroGL is awesome, thanks a lot for a really nice piece of software!

**Comment by neurolabusc** [comment]
Thanks. This will be fixed in the upcoming release which now uses [Python27-for-Lazarus](https://github.com/neurolabusc/Python27-for-Lazarus).
