### ISSUE TITLE
add new option to not modulate alpha by voxel value?

### ISSUE THREAD

**Issue by hanayik** [rordenlab/MRIcroGL12#21]
MRIcroGL version: 1.2.20200707e Cocoa x86-64

@neurolabusc , some regions with low integer values in atlases rendered in 3D mode appear more transparent than high integer label regions. 

For example, an atlas image with integer labels ranging from 1-140 (background == 0) will render regions with low values (1,2,3...) as more transparent. 

Would it be possible to add a toggle setting in preferences to disable alpha modulation by voxel intensity?

No rush on this. Just submitting the issue as a possible enhancement for the future. 

FSLeyes has recently added this feature in the master branch (not released), and it can be useful to toggle that switch when viewing some images. 

I would be happy to help implement this. It would take some time to get up to speed with the MRIcroGL build system and code base. 

https://git.fmrib.ox.ac.uk/fsl/fsleyes/fsleyes/-/blob/master/assets/gl/gl21/glvolume_3d_frag.glsl#L404

https://github.com/rordenlab/MRIcroGL12/blob/70d20ec1f1fb913e7efe5861e8d9dbb6ac77f52b/Resources/shader/Default.glsl#L51

atlas shown in screenshots:

https://git.fmrib.ox.ac.uk/open-science/UK_biobank_pipeline_v_1/-/raw/master/templates/GMatlas/GMatlas.nii.gz?inline=false

## example MRIcroGL screenshot:

<img width="877" alt="Screenshot 2021-03-03 at 17 48 00" src="https://user-images.githubusercontent.com/5217720/109849499-57a7be80-7c49-11eb-8341-7a5aed2f938f.png">

## FSLeyes with intensity modulation

<img width="1674" alt="Screenshot 2021-03-03 at 17 58 36" src="https://user-images.githubusercontent.com/5217720/109850465-73f82b00-7c4a-11eb-806d-6b0c7ec9396c.png">

## FSLeyes WITHOUT intensity modulation

<img width="1677" alt="Screenshot 2021-03-03 at 17 59 05" src="https://user-images.githubusercontent.com/5217720/109850533-84a8a100-7c4a-11eb-8aa5-5ed883198369.png">

**Comment by neurolabusc** [comment]
@hanayik this is an issue with FSL not MRIcroGL. The NIfTI header does not correctly specify the `intent_code` as [NIFTI_INTENT_LABEL](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h). If this is set, the image will be displayed correctly with MRIcroGL. Please fix upstream.

![atlas](https://user-images.githubusercontent.com/8930807/109906639-b96e2580-7c55-11eb-9674-be2497f80545.png)

**Comment by hanayik** [comment]
Nice, that's an easy solution! Thanks @neurolabusc!
