### ISSUE TITLE
Add Overlay (remove small clusters)

### ISSUE THREAD

**Issue by neurolabusc** [rordenlab/MRIcroGL12#4]
MRIcroGL 1.0 had a menu item "Add Overlay (remove small clusters)" - it would be nice to include this in MRIcroGL 1.2. In the meantime, users can use the Matlab script [nii_threshreslicecluster.m](https://github.com/rordenlab/spmScripts/blob/master/nii_threshreslicecluster.m).

Suggested by [Jake](https://www.nitrc.org/forum/forum.php?thread_id=10532&forum_id=4441).

**Comment by da-wi** [comment]
Thank you very much for the matlab script. I second the request to bring back the "remove small clusters" option for overlays!

**Comment by neurolabusc** [comment]
@da-wi if you have MacOS, you can test out this [beta version](https://drive.google.com/file/d/1_Elbf5bjQ_Q7vgcjxywRCls5o-OxAund/view?usp=sharing). You can cluster-threshold any layer using the "Option" menu.

![clusters](https://user-images.githubusercontent.com/8930807/64616204-16af5080-d3aa-11e9-8f9d-d7f08896733c.png)

**Comment by da-wi** [comment]
@neurolabusc thanks for the fast reply, unfortunately we don't run any MacOS machines in our lab, but only Windows. So far, the MATLAB tresholding workaround is working fine.

**Comment by neurolabusc** [comment]
@dw-wi can you re-download the Windows release from [NITRC](https://www.nitrc.org/projects/mricrogl) - this should provide v1.2.20190902+ for Windows, Linux and MacOS. Please test as this is an experimental feature.

**Comment by neurolabusc** [comment]
@da-wi I have updated the main downloads, which should report [v1.2.20190902++](https://www.nitrc.org/projects/mricrogl/). This version corrects to replaced volume size. I describe it [here](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage#Cluster_Thresholds), including a scripting example.
