### ISSUE TITLE
How to script slicing 2D Slices with custom depth, azimuth, and elevation?

### ISSUE THREAD

**Issue by Noob-PeNguiN** [rordenlab/MRIcroGL12#66]
Greetings.
To start with, I just want to say that it's a really great software! And the following is my problem.
I found out that in the clipping section of the software, by setting the depth, azimuth, elevation (and need to set thickness to minimum 
so that it looks like a 2D picture), we can get a slice of the volume. And we can get a slice that is not a coronal, axial or sagittal slice by that, which is what I want. 
But I wonder how can i write a script to do that efficiently in the `scripting` section? I want to put it in a for loop and clip some 2D picture then save the picture and the corrisponding depth, azimuth and elevation of the clipping. I've tried to write the script myself but I've encoutered 2 problems.
- I tried to use the `gl.clipazimuthelevation()` function in your documentation but I don't know if I can set the thickness with it. I tried to set it in the 4th parameter but it just reports error. And without setting the thickness to minimum, I don't know whether can get a good 2D picture, because when the thickness is not minimum, when I turned the exposed surface to the screen, it kind of have some background as it's a 3D volume. Something like this picture below 
![image](https://github.com/user-attachments/assets/cd5c10fb-30d0-460a-a81f-5389973ffaf7)
And if the thickness is set to minimum, it's a resonably good 2D slice
![image](https://github.com/user-attachments/assets/5a3a8c53-b528-4d49-9166-a45032934bf0)

- Also, I don't know how to save the sliced image. I tried to run some of the script in your documentation with functions like  `gl.savebmp(str(x)+'.png')` , I can't found where the saved png is. And when I click `Graph --> Save As Bitmap` for this
![image](https://github.com/user-attachments/assets/835bd502-7f43-4b00-a901-c7a08de1eb7f)
I can only get this, only a white line (the following is not an Dividing Line but the picture I saved)
![saveBitmapTest](https://github.com/user-attachments/assets/2526107e-80b2-472a-b19f-55b658da3908)

**Comment by neurolabusc** [comment]
A nice example of how to do precisely this is demo you see if you choose the Scripting/Template/Explode.

1. Notice the script uses `gl.clipthick(thick)` where `thick is the desired slice thickness - with smaller values leading to thinner slice thicknesses. You can edit the script and choose the Scripting/Run menu item to see the results of your modified script.
2. Notice you can uncomment the last line of code by removing the `#` from the line `#gl.savebmp(str(x)+'.png')` to have the script save the bitmaps to disk.
3. If you do not specify the folder for `savebmp`, MRIcroGL will need to find a location on your hard drive where you have write permissions. For most Unix distributions (MacOS, Linux), this will be the root of your home folder `~`, while for Windows this will be the user's Documents folder.
4. Notice that you can provide an explicit path to the folder where you want to save your bitmaps. You should select an existing folder where you have write permissions. For me, I can save images with the line `gl.savebmp('/Users/chris/src/' + str(x)+'.png')`


![6](https://github.com/user-attachments/assets/f6a641c3-b871-4eae-b3ab-535242e51d1f)

**Comment by Noob-PeNguiN** [comment]
Many thanks for your detailed reply! : )
Now I can save the image smoothly. But I have another question.
When I save the image with this script
``` python
import gl
import os
run = 1
ksteps = 18
ktime= 100
thick = 0.0001
gl.resetdefaults()
gl.loadimage('spm152')
gl.overlayload('spmMotor')
gl.minmax(1, 4, 4)
gl.shaderadjust('boundThresh', 0.35)
gl.shaderadjust('edgeThresh', 0.42)
gl.shaderadjust('edgeBoundMix',0.05)
gl.shaderadjust('colorTemp', 0.8)
gl.backcolor(255, 255,255)
gl.clipazimuthelevation(0.36, 0, 180)
gl.clipthick(thick)
gl.shaderadjust('overlayClip', 1)
datas = []
output_dir = 'D:\\MicroGL_output\\run{0}\\'.format(run)
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

for x in range(1, ksteps):
  depth = 0.1+((x-1)*thick*100)
  # azimuth = 15 * (x-1)
  azimuth = 0
  elevation = 10 * (x-1)
  gl.clipazimuthelevation(0.1+((x-1)*thick*100), azimuth, elevation);
  gl.wait(ktime)
  filename = 'depth_' + str(int(depth*100)) + '_azimuth_'+ str(azimuth) + '_elevation_' + str(elevation)
  para = str(depth) + ' '+ str(azimuth) + ' ' + str(elevation) + '\n'
  gl.savebmp(output_dir + filename +'.png')
  datas.append(para)

with open(output_dir + 'output.txt', "w") as file:
  file.writelines(datas)
```
the image I get looks like this
![depth_26_azimuth_0_elevation_160](https://github.com/user-attachments/assets/ee810adc-b6e6-42e1-bef2-0aa880c41ef1)
But what I really want is sth like this -- the slice facing the screen vertically rather thant obliquely (also without other things from the ui like the LSA cube and the color bar). I could't find a function to do it. In the `Display` section of the software I can choose directions like Posterior, Anterior and so on, but since I sliced then in neither of those directions, it didn't work. (also, I need to process data in batches, so at the end of the day I'll still need sth I can write a script with).
Many thanks for your time to read this and looking forward to your reply!
![image](https://github.com/user-attachments/assets/aa63f6ec-cb77-43a4-a853-19f27a5d42fe)

**Comment by neurolabusc** [comment]
1. You can see all of the Python commands by choosing Scripting/Templates/Help which will output a text file into the text panel directly below the script.
2. The help file suggests you can hide the colorbar with `gl.colorbarposition(0)` and change the location of the camera with `gl.azimuthelevation(0,90)`.
3. I am not sure if you can toggle the orientation cube with a script, but you can toggle it with the `Text and orientation cube` menu item in the `View` menu.

Putting this together, a script would look like this:

```python
import gl
ksteps = 12
ktime= 100
thick = 1.0/ksteps
gl.resetdefaults()
gl.colorbarposition(0)
gl.loadimage('spm152')
gl.overlayload('spmMotor')
gl.minmax(1, 4, 4)
gl.shaderadjust('boundThresh', 0.35)
gl.shaderadjust('edgeThresh', 0.42)
gl.shaderadjust('edgeBoundMix',0.05)
gl.shaderadjust('colorTemp', 0.8)
gl.backcolor(255, 255,255)
gl.clipthick(thick)
gl.shaderadjust('overlayClip', 1)
gl.azimuthelevation(0,90)
for x in range(1, ksteps):
  gl.clipazimuthelevation(0.001+((x-1)*thick), 0, 90);
  gl.wait(ktime)
  #gl.savebmp(str(x)+'.png')
```

**Comment by Noob-PeNguiN** [comment]
Many thanks for your detailed and timely reply!! : )
I tried to use the `gl.azimuthelevation()` function to make the camera orientation right, and it works perfectly when I only change azimuth or elevation at a time. But when I change them simultaneously, the camera orientation is not 100% perpendicular to the image, and I don't know why would this happen.
It looks sth like this
![image](https://github.com/user-attachments/assets/502ff02d-fc8d-40e4-af41-e4a3fcb01ed3)
Rather than this, which I toggled it manually so that the camera face perpendicular to the image (at least closer to perpendicular than the above image)
![image](https://github.com/user-attachments/assets/dc6209aa-c122-41c6-a786-33e7fd4f34a4)
And here's my script
```python
import gl
import os
run = 1
ksteps = 18
ktime= 100
thick = 0.0001
gl.resetdefaults()
gl.colorbarposition(0)
gl.loadimage('spm152')
gl.overlayload('spmMotor')
gl.minmax(1, 4, 4)
gl.shaderadjust('boundThresh', 0.35)
gl.shaderadjust('edgeThresh', 0.42)
gl.shaderadjust('edgeBoundMix',0.05)
gl.shaderadjust('colorTemp', 0.8)
gl.shaderquality1to10(10)
gl.backcolor(255, 255,255)
gl.clipazimuthelevation(0.36, 0, 180)
gl.clipthick(thick)
gl.shaderadjust('overlayClip', 1)
gl.zoomscale(6)
datas = []
output_dir = 'D:\\MicroGL_output\\run{0}\\'.format(run)
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

for x in range(1, ksteps):
  depth = 0.1+((x-1)*thick*100)
  # depth = 0.3
  azimuth = 10 * (x-1)
  # azimuth = 0
  elevation = 10 * (x-1)
  gl.clipazimuthelevation(0.1+((x-1)*thick*100), azimuth, elevation)
  gl.azimuthelevation(azimuth, elevation)
  gl.wait(ktime)
  filename = 'depth_' + str(int(depth*100)) + '_azimuth_'+ str(azimuth) + '_elevation_' + str(elevation)
  para = str(depth) + ' '+ str(azimuth) + ' ' + str(elevation) + '\n'
  gl.savebmp(output_dir + filename +'.png')
  datas.append(para)

with open(output_dir + 'output.txt', "w") as file:
  file.writelines(datas)
```
Many many thanks for your time to read this and looking forward to your reply!

**Comment by neurolabusc** [comment]
This is the expected behavior. Your script is varying both the camera position (azimuthelevation) and the clip plane (clipazimuthelevation) with each frame. In my example, I used a fixed camera position and adjusted only the clip plane with each frame. If you want a camera that is perpendicular to your image, you should position your camera at the orthogonal azimuth (0, 90, 180, 270 degrees) and elevation (-90, 0, 90) from your object. Adjusting the camera position by 10-degree steps will generate oblique views.

**Comment by Noob-PeNguiN** [comment]
Thanks for your reply!!! : )
I tried to calculate the azimuth and elevation of the normal vector of the clip plane and set the camera position to the normal vector,but the image I get is still oblique. I think my calculation of the normal is correct, so is it that I understand how the coordinate system work in the `gl.clipazimuthelevation()` and `gl.azimuthelevation()` wrong?
The following is my code
```python
import gl
import os
import math

def get_camera_angles(cut_azimuth, cut_elevation):
    # degree to radian
    az_rad = math.radians(cut_azimuth)
    el_rad = math.radians(cut_elevation)

    # the normal of the surface
    x = math.cos(el_rad) * math.sin(az_rad)
    y = math.cos(el_rad) * math.cos(az_rad)
    z = math.sin(el_rad)

    # turn it to azimuth and elevation
    camera_azimuth = math.degrees(math.atan2(x, y)) % 360
    camera_elevation = math.degrees(math.asin(z))

    return camera_azimuth, camera_elevation


run = 1
ksteps = 15
ktime = 100
thick = 0.0001

gl.resetdefaults()
gl.colorbarposition(0)
gl.loadimage('spm152')
gl.overlayload('spmMotor')
gl.minmax(1, 4, 4)
gl.shaderadjust('boundThresh', 0.35)
gl.shaderadjust('edgeThresh', 0.42)
gl.shaderadjust('edgeBoundMix', 0.05)
gl.shaderadjust('colorTemp', 0.8)
gl.shaderquality1to10(10)
gl.backcolor(255, 255, 255)

gl.clipthick(thick)
gl.shaderadjust('overlayClip', 1)
gl.zoomscale(6)

datas = []
output_dir = 'D:\\MicroGL_output\\run{0}\\'.format(run)
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

for x in range(1, ksteps):
    depth = 0.1 + ((x-1) * thick * 100)
    
    # an arbitrary azimuth an elecation
    azimuth = 10 * (x-1) 
    elevation = 10 * (x-1)  

    # calculate camera position
    camera_azimuth, camera_elevation = get_camera_angles2(azimuth, elevation)

    # adjust the clip plane
    gl.clipazimuthelevation(depth, azimuth, elevation)
    
    # adjust the camera position
    gl.azimuthelevation(round(camera_azimuth), round(camera_elevation))

    gl.wait(ktime)
```
Many many thanks for your time to read this and looking forward to your reply!

**Comment by neurolabusc** [comment]
MRIcroGL is behaving as requested. I guess I do not understand what result you are trying to achieve. You do want to consider the frame of reference used - perhaps the azimuth should have the reverse polarity for the clip plane and the camera position. 

```python
import gl
ksteps = 12
ktime= 100
thick = 0.5/ksteps
gl.resetdefaults()
gl.loadimage('spm152')
gl.overlayload('spmMotor')
gl.minmax(1, 4, 4)
gl.shaderadjust('boundThresh', 0.35)
gl.shaderadjust('edgeThresh', 0.42)
gl.shaderadjust('edgeBoundMix',0.05)
gl.shaderadjust('colorTemp', 0.8)
gl.backcolor(255, 255,255)
gl.clipazimuthelevation(0.36, 0, 180)
gl.clipthick(thick)
gl.shaderadjust('overlayClip', 1)
for x in range(1, ksteps):
  azi = x * 10
  elev = x * 5
  gl.clipazimuthelevation(0.2, azi, elev);
  gl.azimuthelevation(-azi,elev)
  gl.wait(ktime)
```

**Comment by Noob-PeNguiN** [comment]
Thanks for your reply and sorry for my late reply !
> The result I'm trying to achieve

I tried to clip the plane with an rather arbitrary azimuth and elevation so that I can get a image different from the traditional coronal, axial and sagittal view, sth like this (I incresed the thickness so it would be easier to see, but in pratice I would set it to the minimum so that it would be more like a slice)
![image](https://github.com/user-attachments/assets/4d537279-17ef-475e-a871-df46d095128e)

> The azimuth should have the reverse polarity for the clip plane and the camera position.

Yes, this is vital, when I change my code to `gl.azimuthelevation(-azi,elev)` it works perfectly! Now the resulting image doesn't have any oblique. 

Thanks again for your time! : )

Btw, for those who might want to do the same thing, here's my code for your reference.
```python
import gl
import os

run = 2
ksteps = 18
ktime= 100
thick = 0.0001

gl.resetdefaults()
gl.colorbarposition(0)
gl.loadimage('spm152')
gl.overlayload('spmMotor')
gl.minmax(1, 4, 4)
gl.shaderadjust('boundThresh', 0.35)
gl.shaderadjust('edgeThresh', 0.42)
gl.shaderadjust('edgeBoundMix',0.05)
gl.shaderadjust('colorTemp', 0.8)
gl.shaderquality1to10(10)
gl.backcolor(255, 255,255)
gl.clipazimuthelevation(0.36, 0, 180)

gl.clipthick(thick)
gl.shaderadjust('overlayClip', 1)
gl.zoomscale(6)

datas = []
output_dir = 'D:\\MicroGL_output\\run{0}\\'.format(run)
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

for x in range(1, ksteps):
  depth = 0.1+((x-1)*thick*100)
  # depth = 0.3
  azimuth = 15 * (x-1)
  # azimuth = 0
  elevation = 10 * (x-1)
  gl.clipazimuthelevation(0.1+((x-1)*thick*100), azimuth, elevation)
  gl.azimuthelevation(-azimuth, elevation)
  gl.wait(ktime)
  filename = 'depth_' + str(int(depth*100)) + '_azimuth_'+ str(azimuth) + '_elevation_' + str(elevation)
  para = str(depth) + ' '+ str(azimuth) + ' ' + str(elevation) + '\n'
  gl.savebmp(output_dir + filename +'.png')
  datas.append(para)

with open(output_dir + 'output.txt', "w") as file:
  file.writelines(datas)
```
