### ISSUE TITLE
Can I save a novel NIfTI stack with saveimg()?

### ISSUE THREAD

**Issue by Noob-PeNguiN** [rordenlab/MRIcroGL12#68]
Hi, I'm the guy from [issue66](https://github.com/rordenlab/MRIcroGL/issues/66), and I have some few more question.
I was looking through your python command documentation today and found this.
`saveimg (built-in function): saveimg(filename) -> Save background image (layer 0) to disk. For example "saveimg('test.nii')", extension defines type (.nii=NIfTI, .osp=ospray, .bvox=blender)`
So, does it mean that I can save a NIfTI stack with it? Then can I use this function to save stacks in different orientations? (If I change parameters like azimuth and elevation, will it save in that orientation?) In this way, I think I can do what I want to do in  [issue66](https://github.com/rordenlab/MRIcroGL/issues/66) easier. I can simply change the perspective of the NIfTI file and save it, getting a novel view slice won't be a problem since we just need to get the data from the NIfTI file saved after changing the perspective (e.g. running nibabel's .get_fdata())

**Comment by neurolabusc** [comment]
The `azimuthelevation()` function changes the location of the camera, not the orientation of the object. The `saveimg()` command is a way to change the image format (e.g. to convert a NIfTI image into an ospray image). MRIcroGL does allow you to reslice data to a new orientation using the Import/Tools/Rotation menu items to interactively select spatial directions, but this is not available from scripting. If you want to automate reorienting NIfTI images, I would use nibabel to either change the `affine` (the image s-form) or reorder/reflect the dimensions of the voxel image.

**Comment by Noob-PeNguiN** [comment]
Hi, sorry for my late reply.
I get it now, thanks! : )
