### ISSUE TITLE
Opening multiple windows

### ISSUE THREAD

**Issue by orange-swan** [rordenlab/MRIcroGL12#8]
Hello!

I‘m using MRIcroGL on macOS 10.14.6. Is it the intended behavior, that opening multiple images side by side (multiple windows) is a bit complicated? If MRIcroGL is open, double clicking another file in the Finder doesn‘t open it in a new window, but instead uses the existing one. I have to manually open a new window from the menu (as there‘s no shortcut for it) and then open the file I want. If I forget this step, I have to manually reopen the one from before, again after opening a new window. Am I missing something?

Thanks!

**Comment by neurolabusc** [comment]
This is a feature of using MacOS. With Linux and Windows you can launch separate instances from the file explorer. Perhaps in the next release we could add a shortcut like Shift+Command+N to open a new window.
