### ISSUE TITLE
Color when saving as bitmap becomes blue

### ISSUE THREAD

**Issue by yehman** [rordenlab/MRIcroGL12#9]
Somehow, whenever I use the save as bitmap function, images come out with blue tint, especially for overlay images.  Attached are the screenshot of the console, and the image generated with save as bitmap.

I'm using the precompiled MRIcroGL 1.2.20190902++ GTK2 on Linux.  Load up any image and overlay, and overlay color will come out with blue tint when saved as bitmap.

Screenshot:
![Screenshot from 2019-11-22 19:48:50](https://user-images.githubusercontent.com/11858247/69472653-b05b8c80-0d61-11ea-837f-bbe476a323a9.png)

Saved file:
![bitmapsave](https://user-images.githubusercontent.com/11858247/69472710-5effcd00-0d62-11ea-9915-af925cafe8f1.png)

**Comment by neurolabusc** [comment]
Acknowledged, specific to Linux. Will be resolved in next release.

**Comment by neurolabusc** [comment]
Fixed in latest release (v1.2.20200331)
